replicaCount: 1


project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

port: 8080

image:
  name: "giantswarm/webhook-exporter"
  tag: "[[ .Version ]]"
  pullPolicy: IfNotPresent

registry:
  domain: quay.io

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
