version: 2.1

orbs:
  architect: giantswarm/architect@4.17.0

jobs:
  test:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: CGO_ENABLED=0 make test

workflows:
  build:
    jobs:
      - test
      - architect/go-build:
          name: go-build
          binary: webhook-exporter
          filters:
            tags:
              only: /^v.*/
          pre-steps:
            - checkout
            - run:
                command: CGO_ENABLED=0 make manifests && make generate && make envtest && KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)"

      - architect/push-to-docker:
          context: "architect"
          name: push-webhook-exporter-to-quay
          image: "quay.io/giantswarm/webhook-exporter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - test
          # Needed to trigger job als on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-webhook-exporter-to-docker
          image: "docker.io/giantswarm/webhook-exporter"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - test
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-webhook-exporter-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/webhook-exporter"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-webhook-exporter-to-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "webhook-exporter"
          requires:
            - push-webhook-exporter-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

