version: 2.1

orbs:
  architect: giantswarm/architect@4.17.0

jobs:
  test_and_build:
    executor: architect/architect
    steps:
      - checkout
      - run: |
          go mod tidy && git diff --exit-code
      - run: |
          echo -n "-w -linkmode 'auto' -extldflags '-static'" > .ldflags
      - run: >
          echo -n " -X '$(go list .)/pkg/project.buildTimestamp=$(date --utc
          '+%FT%TZ')'" >> .ldflags
      - run: |
          echo -n " -X '$(go list .)/pkg/project.gitSHA=${CIRCLE_SHA1}'" >> .ldflags
      - run: |
          echo "\"$(cat .ldflags)\""
      - run:
          command: >
            go install golang.org/x/tools/cmd/goimports@latest && if [[ -n
            $(goimports -local
            github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -l .)
            ]]; then goimports -local
            github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -d . &&
            exit 1; fi
          name: Check if imports are properly sorted
      - run: |
          test -z $(gofmt -l .) || gofmt -d .
      - run: |
          CGO_ENABLED=0 go vet ./...
      - run: |
          CGO_ENABLED=0 golangci-lint run -E gosec -E goconst
      - run: >
          CGO_ENABLED=0 go list -json -m all | nancy sleuth --skip-update-check
          --quiet
      - run:
          name: "Run tests"
          command: CGO_ENABLED=0 make test

workflows:
  build:
    jobs:
      - test_and_build
      - architect/push-to-docker:
          context: "architect"
          name: push-webhook-exporter-to-quay
          image: "quay.io/giantswarm/webhook-exporter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - test_and_build
          # Needed to trigger job als on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-webhook-exporter-to-docker
          image: "docker.io/giantswarm/webhook-exporter"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - test_and_build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-webhook-exporter-to-app-catalog
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "webhook-exporter"
          requires:
            - push-webhook-exporter-to-quay
            - push-webhook-exporter-to-docker
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
