version: 2.1

orbs:
  architect: giantswarm/architect@4.17.0

jobs:
  tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: CGO_ENABLED=0 make test
  build:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: CGO_ENABLED=0 make test
      - architect/go-build:
          binary: webhook-exporter 
          os: linux
    

workflows:
  build:
    jobs:
      - build
      - architect/push-to-docker:
          context: "architect"
          name: push-webhook-exporter-to-quay
          image: "quay.io/giantswarm/webhook-exporter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          # Needed to trigger job als on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-webhook-exporter-to-docker
          image: "docker.io/giantswarm/webhook-exporter"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

