apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ include "resource.default.name" . }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - apiregistration.k8s.io
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - apps
    resources:
      - deployments
      - poddisruptionbudgets
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "resource.default.name" . }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: "{{ include "resource.default.name" . }}"
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: "{{ include "resource.default.name" . }}"
    namespace: {{ .Release.Namespace }}
